Build and publish Staging- files to S3 in Travis
OneSignal/OneSignal-Website-SDK pull request #706
Opened 2020-09-23 22:02 UTC by terrynsun

Staging- files are currently served from rails on staging-01, but we'd
like them to be served by turbine instead, as in prod, and to simplify
URL routing. This change pushes Staging- files to S3, so turbine can
download and serve them.

https://onesignal.atlassian.net/browse/OS-5032

# Systems Affected
   - [X] WebSDK
   - [ ] Backend
   - [ ] Dashboard

2020-09-24 00:13 UTC, RyanAmos reviewed
Will let @jkasten2  review this since he knows better wether there's any issues here.

2020-09-24 15:40 UTC, jkasten2 requested changes

2020-09-24 15:40 UTC, jkasten2 commented on .travis.yml
> +  - yarn build:staging
The staging URLs need to be pass into this command as they are not provided in this repo. I recommend we provide them via environment variables via TravisCI.

The full command should looks something like:
```bash
BUILD_ORIGIN=${STAGING_DOMAIN} API=staging API_ORIGIN=${STAGING_DOMAIN} yarn build:staging
```

2020-09-24 15:40 UTC, jkasten2 commented on .travis.yml
> +  - yarn build:staging
There is an extra step that needs to be done to correct source maps that are being done manually today.

```bash
sed -i 's/sourceMappingURL=OneSignal/sourceMappingURL=Staging-OneSignal/' Staging-*.js
sed -i 's/sourceMappingURL=OneSignal/sourceMappingURL=Staging-OneSignal/' Staging-*.css
```

2020-10-01 21:26 UTC, jkasten2 commented on build/scripts/publish.sh
> +  sed -i 's/sourceMappingURL=OneSignal/sourceMappingURL=Staging-OneSignal/' Staging-*.css
TravisCI failed due to not being able to find these files. I think we need to add `build/releases/` to the files being edited here.
Thinking this should fix it.
```
	  sed -i 's/sourceMappingURL=OneSignal/sourceMappingURL=Staging-OneSignal/' build/releases/Staging-*.js
    sed -i 's/sourceMappingURL=OneSignal/sourceMappingURL=Staging-OneSignal/' build/releases/Staging-*.css
```

2020-10-01 21:26 UTC, jkasten2 requested changes
See my last comment above

2020-10-01 21:40 UTC, jkasten2 approved these changes

2020-10-01 21:45 UTC, merged