Updated setEmail() and setExternalUserId() calls to make sure they ar…
OneSignal/OneSignal-Website-SDK pull request #713
Opened 2020-10-21 05:40 UTC by grevolution

…e checking for external user id

# Description
## 1 Line Summary

## Details

# Systems Affected
   - [ ] WebSDK
   - [ ] Backend
   - [ ] Dashboard

# Validation
## Tests
### Info

### Checklist
   - [ ] All the automated tests pass or I explained why that is not possible
   - [ ] I have personally tested this on my machine or explained why that is not possible
   - [ ] I have included test coverage for these changes or explained why they are not needed

**Programming Checklist**
Interfaces:
   - [ ] Don't use default export
   - [ ] New interfaces are in model files

Functions:
   - [ ] Don't use default export
   - [ ] All function signatures have return types
   - [ ] Helpers should not access any data but rather be given the data to operate on.

Typescript:
   - [ ] No Typescript warnings
   - [ ] Avoid silencing null/undefined warnings with the exclamation point

Other:
   - [ ] Iteration: refrain from using `elem of array` syntax. Prefer `forEach` or use `map`
   - [ ] Avoid using global OneSignal accessor for `context` if possible. Instead, we can pass it to function/constructor so that we don't call `OneSignal.context`

## Screenshots
### Info

### Checklist
   - [ ] I have included screenshots/recordings of the intended results or explained why they are not needed

---

## Related Tickets

---

2020-10-21 05:46 UTC, grevolution commented
fixes #713

2020-11-17 23:13 UTC, rgomezp commented
Howdy,
You linked this same PR when noting the issue that it fixes. Can you please include the correct issue for context?

2020-11-17 23:17 UTC, rgomezp commented on src/OneSignal.ts
> +    var sanitizedExternalUserId: string | undefined;
use `let` or `const`

2020-11-18 00:33 UTC, grevolution commented
> Howdy,
> You linked this same PR when noting the issue that it fixes. Can you please include the correct issue for context?

Done.

2020-11-18 00:38 UTC, grevolution commented on src/OneSignal.ts
> +    var sanitizedExternalUserId: string | undefined;
Done.

2020-11-18 04:07 UTC, jkasten2 requested changes
Left some feedback below.
Also would helpful to add some tests to cover this logic chane

2020-11-18 04:07 UTC, jkasten2 commented on src/OneSignal.ts
> +    if(externalUserId == null){
nit, missing space after both if and ), should be:
```typescript
if (externalUserId == null) {
```

2021-04-23 21:46 UTC, jkasten2 commented
This is now fixed in PR #797 and has been released in version [151403](https://github.com/OneSignal/OneSignal-Website-SDK/releases/tag/151403).

2021-04-23 21:46 UTC, closed without merging