fix(urls): tiny urls fixed for init errors
OneSignal/OneSignal-Website-SDK pull request #767
Opened 2021-03-16 18:10 UTC by devpato

# Description
## 1 Line Summary

## Details
 Based on the ticket Web SDK was being tested locally and user ran into an error, which points to a URL https://goo.gl/xip6JB that no longer exists. As you can see I modified 2 links instead of one because both of the links were down.

# Systems Affected
   - [] WebSDK
   - [ ] Backend
   - [ ] Dashboard

# Validation
## Tests
### Info

### Checklist
   - [ ] All the automated tests pass or I explained why that is not possible
   - [ ] I have personally tested this on my machine or explained why that is not possible
   - [ ] I have included test coverage for these changes or explained why they are not needed

**Programming Checklist**
Interfaces:
   - [ ] Don't use default export
   - [ ] New interfaces are in model files

Functions:
   - [ ] Don't use default export
   - [ ] All function signatures have return types
   - [ ] Helpers should not access any data but rather be given the data to operate on.

Typescript:
   - [ ] No Typescript warnings
   - [ ] Avoid silencing null/undefined warnings with the exclamation point

Other:
   - [ ] Iteration: refrain from using `elem of array` syntax. Prefer `forEach` or use `map`
   - [ ] Avoid using global OneSignal accessor for `context` if possible. Instead, we can pass it to function/constructor so that we don't call `OneSignal.context`

## Screenshots
### Info

### Checklist
   - [ ] I have included screenshots/recordings of the intended results or explained why they are not needed

---

## Related Tickets
https://app.asana.com/0/1193807006058450/1199616780744182/f
---

2021-03-16 19:36 UTC, jkasten2 requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/767)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @devpato, @jkasten2, and @rgomezp)

___
*[src/errors/SdkInitError.ts, line 27 at r1](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/767#-MVwEMak8u6oP9-B9rtV:-MVwEMak8u6oP9-B9rtW:b-anqc13) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/dd99de74a5576f69adde39682bbaa2c624b51b7f/src/errors/SdkInitError.ts#L27)):*
> ```XML
>       case SdkInitErrorKind.AppNotConfiguredForWebPush:
>         errorMessage = `OneSignal: This app ID does not have any web platforms enabled. Double check your app` +
>         ` ID, or see step 1 on our setup guide ( https://documentation.onesignal.com/docs/web-push-typical-setup).`;
> ```

nit, looks like an extra space was added after `(`.
___
*[src/errors/SdkInitError.ts, line 30 at r1](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/767#-MVwEqOIEn3oEAu-Axc_:-MVwEqOIEn3oEAu-Axca:bbpstvs) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/dd99de74a5576f69adde39682bbaa2c624b51b7f/src/errors/SdkInitError.ts#L30)):*
> ```XML
>         break;
>       case SdkInitErrorKind.MissingSubdomain:
>         errorMessage = `Non-HTTPS pages require the subdomainName parameter within the label set within the OneSignal Web configuration (https://documentation.onesignal.com/docs/web-push-sdk#initialization).`;
> ```

Wow forgot about this check, I believe if you setup an HTTP site with either as "Custom Code" or "Typical Site" the code snip doesn't show `subdomainName`.

We can update this link for now in this PR to keep this one simple however.


<!-- Sent from Reviewable.io -->

2021-03-16 19:37 UTC, jkasten2 approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/767)* status: all files reviewed, 1 unresolved discussion (waiting on @devpato and @rgomezp)



<!-- Sent from Reviewable.io -->

2021-03-17 19:12 UTC, jkasten2 approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/767)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rgomezp)



<!-- Sent from Reviewable.io -->

2021-03-17 23:09 UTC, rgomezp approved these changes

2021-03-22 18:51 UTC, merged