Web Prompts Styles and Validation
OneSignal/OneSignal-Website-SDK pull request #768
Opened 2021-03-16 22:27 UTC by rgomezp

# Description
## 1 Line Summary
Slidedown Channel Capture container implementation with validation and styling

## Details
### Styling
New sass styles for the Web Prompts slidedown. One consideration to keep in mind is the conflict with the [International Telephone Input](https://github.com/jackocnr/intl-tel-input) library styles. This PR includes changes to the "reset styles" that works around this issue. The way it works is by excluding the reset styles from classes that start with "iti."

### Validation
Validation is done for both the sms and email fields. The two work slightly differently. We access the latest validation state for both input types via a `ChannelCaptureContainer` member variable that is updated on every `keyup` or `focus` event. These variables are then accessed on the `ALLOW_CLICK` event to throw an error or continue with the updating of the player records.

#### SMS Validation
Uses the [3rd party library's](https://github.com/jackocnr/intl-tel-input#getting-started-not-using-a-bundler) validation function to update the `smsInputFieldIsValid` variable of the `ChannelCaptureContainer`. 

#### Email Validation
Uses regex to update the `smsInputFieldIsValid` variable of the `ChannelCaptureContainer`. 

# Systems Affected
   - [x] WebSDK
   - [ ] Backend
   - [ ] Dashboard

# Validation
## Tests
### Info

### Checklist
   - [ ] All the automated tests pass or I explained why that is not possible
   - [ ] I have personally tested this on my machine or explained why that is not possible
   - [ ] I have included test coverage for these changes or explained why they are not needed

**Programming Checklist**
Interfaces:
   - [ ] Don't use default export
   - [ ] New interfaces are in model files

Functions:
   - [ ] Don't use default export
   - [ ] All function signatures have return types
   - [ ] Helpers should not access any data but rather be given the data to operate on.

Typescript:
   - [ ] No Typescript warnings
   - [ ] Avoid silencing null/undefined warnings with the exclamation point

Other:
   - [ ] Iteration: refrain from using `elem of array` syntax. Prefer `forEach` or use `map`
   - [ ] Avoid using global OneSignal accessor for `context` if possible. Instead, we can pass it to function/constructor so that we don't call `OneSignal.context`

## Screenshots
### Info

### Checklist
   - [ ] I have included screenshots/recordings of the intended results or explained why they are not needed

---

## Related Tickets

---

2021-03-16 22:53 UTC, rgomezp commented on src/slidedown/ChannelCaptureContainer.ts
> +    static resetInputErrorStates() {
void return type

2021-03-18 00:47 UTC, jkasten2 requested changes
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/768)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @rgomezp)

___
*[typings/globals/missing.d.ts, line 32 at r21](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/768#-MW1n-WzE8-ykxv8vg16:-MW1n-X-E1AybZcuQy-8:b-u0esfg) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/b138bd1bbdb8d0e558c1e2ad6a8d8af1ca0f0031/typings/globals/missing.d.ts#L32)):*
> ```XML
> 
> declare var OneSignal: any;
> declare var intlTelInput: any;
> ```

I there a index.d.ts defined for this library?


<!-- Sent from Reviewable.io -->

2021-03-18 01:13 UTC, rgomezp commented on package.json
>      },
ALREADY REVIEWED IN https://github.com/OneSignal/OneSignal-Website-SDK/pull/771

2021-03-18 01:13 UTC, rgomezp commented on src/slidedown/InternationalTelephoneInput.ts
> +export enum ItiScriptURLs {
ALREADY REVIEWED IN https://github.com/OneSignal/OneSignal-Website-SDK/pull/771

2021-03-18 01:14 UTC, rgomezp commented on src/slidedown/ChannelCaptureContainer.ts
> +
Extra line

2021-03-18 01:16 UTC, rgomezp commented on src/slidedown/ChannelCaptureContainer.ts
> +    }
ALREADY REVIEWED IN #769

2021-03-18 01:16 UTC, rgomezp commented on src/slidedown/ChannelCaptureContainer.ts
> +
ALREADY REVIEWED IN #769

2021-03-18 01:17 UTC, rgomezp commented on src/slidedown/ChannelCaptureContainer.ts
> +        }
ALREADY REVIEWED IN #769

2021-03-18 01:17 UTC, rgomezp commented on src/slidedown/ChannelCaptureContainer.ts
> +    }
ALREADY REVIEWED IN #769

2021-03-18 21:10 UTC, rgomezp commented
___
*[typings/globals/missing.d.ts, line 32 at r21](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/768#-MW1n-WzE8-ykxv8vg16:-MW6A9zDAs7Nu4aEYeZv:bqmjwcm) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/b138bd1bbdb8d0e558c1e2ad6a8d8af1ca0f0031/typings/globals/missing.d.ts#L32)):*
<details><summary><i>Previously, jkasten2 (Josh Kasten) wrote…</i></summary><blockquote>

I there a index.d.ts defined for this library?
</blockquote></details>

Added!


<!-- Sent from Reviewable.io -->

2021-03-23 22:08 UTC, jkasten2 requested changes

2021-03-23 22:08 UTC, jkasten2 commented on src/slidedown/ChannelCaptureContainer.ts
> +    private updateValidationOnInputChange(type: DelayedPromptType): void {
Should be two methods. `updateValidationOnEmailChange`  and `updateValidationOnSMSChange`. After that we could clean up more by then making a shared function these to can use to update the CSS ect.

2021-03-24 18:54 UTC, merged