User model/core v2
OneSignal/OneSignal-Website-SDK pull request #910
Opened 2022-09-14 22:47 UTC by rgomezp

# Description
## 1 Line Summary

## Details

# Systems Affected
   - [ ] WebSDK
   - [ ] Backend
   - [ ] Dashboard

# Validation
## Tests
### Info

### Checklist
   - [ ] All the automated tests pass or I explained why that is not possible
   - [ ] I have personally tested this on my machine or explained why that is not possible
   - [ ] I have included test coverage for these changes or explained why they are not needed

**Programming Checklist**
Interfaces:
   - [ ] Don't use default export
   - [ ] New interfaces are in model files

Functions:
   - [ ] Don't use default export
   - [ ] All function signatures have return types
   - [ ] Helpers should not access any data but rather be given the data to operate on.

Typescript:
   - [ ] No Typescript warnings
   - [ ] Avoid silencing null/undefined warnings with the exclamation point

Other:
   - [ ] Iteration: refrain from using `elem of array` syntax. Prefer `forEach` or use `map`
   - [ ] Avoid using global OneSignal accessor for `context` if possible. Instead, we can pass it to function/constructor so that we don't call `OneSignal.context`

## Screenshots
### Info

### Checklist
   - [ ] I have included screenshots/recordings of the intended results or explained why they are not needed

---

## Related Tickets

---

2022-09-19 20:17 UTC, rgomezp commented on src/core/modelRepo/OSModelStore.ts
> +        this.models[model.id] = model;
subscribe models

2022-09-19 20:18 UTC, rgomezp commented on src/core/modelRepo/OSModelStore.ts
> +      this.broadcast(new ModelStoreAdded(model.id, model, noRemoteSync));
use unsubscribe callback to unsub after model removal

2022-09-19 20:33 UTC, rgomezp commented on src/core/operationRepo/Operation.ts
> +    this.id = Math.random().toString(36).substring(2);
consider alternatives

2022-09-19 20:40 UTC, rgomezp commented on src/core/executors/OSExecutorBase.ts
> +        continue;
return

2022-09-19 20:46 UTC, rgomezp commented on src/core/executors/OSExecutorBase.ts
> +        this._enqueueOperation(operation);
add a comment regarding potential changes to retry logic

2022-09-19 20:47 UTC, rgomezp commented on src/core/executors/OSExecutorBase.ts
> +      let res: ExecutorResult = { success: false };
add something like `retriable`

2022-09-19 20:50 UTC, rgomezp commented on src/core/executors/OSExecutorBase.ts
> +    while (this._operationQueue.length > 0) {
clone the array before the iteration

2022-09-19 20:52 UTC, rgomezp commented on src/core/executors/OSExecutorBase.ts
> +        continue;
remove if not fixing a typescript warning

2022-09-19 21:05 UTC, rgomezp commented
prefer `unknown` over `any`, or if you know it'll be non-null use `object`

2022-09-19 21:05 UTC, rgomezp commented
drop `OS` prefix from classes/files

2022-09-19 21:07 UTC, rgomezp commented
make unit test for add, remove model

2022-09-26 20:12 UTC, rgomezp commented on src/core/models/ExecutorResult.ts
> +  result?: any;
see if you can fix the typescript warning and make this non-optional

2022-09-26 20:30 UTC, rgomezp commented on test/unit/core/ModelRepo.ts
> +  const broadcastSpy = sinonSandbox.spy(ModelRepo.prototype as any, "broadcast");
instead of using spies, we have the API to subscribe directly

2022-09-26 20:31 UTC, rgomezp commented on test/unit/core/OSModel.ts
> +  const broadcastSpy = sinonSandbox.spy(OSModel.prototype as any, "broadcast");
subscribe directly

2022-09-26 20:33 UTC, rgomezp commented on test/unit/core/OSModel.ts
> +});
Add test for catching corrupted data not properly decoded

2022-09-26 20:39 UTC, rgomezp commented on test/unit/core/OperationRepo.ts
> +});
see if it makes sense to also inspect the changes on the operation itself (alias values)

2022-09-26 20:56 UTC, rgomezp commented on build/config/tsconfig.base.json
> +      "es2017",
Add details in commit on why this change is needed

2022-09-29 20:53 UTC, rgomezp commented on test/unit/core/OSModel.ts
> +});
TS should prevent this at compile time

2022-09-29 22:01 UTC, jkasten2 requested changes
> Reviewed 59 of 59 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/910)* status: all files reviewed, 1 unresolved discussion (waiting on @brismithers, @emawby, @nan-li, and @rgomezp)

___
*[`src/OneSignalDeprecated.ts` line 1 at r1](https://reviewable.io/reviews/onesignal/onesignal-website-sdk/910#-NDAFZ3Z1BzGDPVCw-CB:-NDAFZ3Z1BzGDPVCw-CC:b4o0h9t) ([raw file](https://github.com/onesignal/onesignal-website-sdk/blob/8807b9174f2a5a8e79ab18ca8f517458e4423120/src/OneSignalDeprecated.ts#L1)):*
> ```XML
> // import bowser from 'bowser';
> ```

Every line in this file has been commented out. Should delete instead if we don't need anything from it.


<!-- Sent from Reviewable.io -->

2022-09-30 18:04 UTC, merged