User model/testing
OneSignal/OneSignal-Website-SDK pull request #995
Opened 2023-02-22 19:48 UTC by rgomezp

# Description
## 1 Line Summary
Sets up the new generation of test coverage with Jest and adds testing for Core Module functionality.

## Details
* Removes AVA tests from CI and replaces with Jest
* Adds test support directory with testing files
* Adds test coverage for Core Module

# Systems Affected
   - [x] WebSDK
   - [ ] Backend
   - [ ] Dashboard

# Validation
## Tests
### Info
All new tests. Does **not** include test coverage for the rest of the codebase.

### Checklist
   - [x] All the automated tests pass or I explained why that is not possible
   - [x] I have personally tested this on my machine or explained why that is not possible
   - [x] I have included test coverage for these changes or explained why they are not needed

2023-02-23 03:47 UTC, jkasten2 requested changes
Looks like a number of files (the ones in `support/mocks/models/` like `MockPushManager.ts`) are not new in this PR but rather just moved. Can we make a change in this PR so it shows up as moves? Might be able to just delete the old files to get that to show, or might have to do `git mv`

2023-02-23 07:13 UTC, jkasten2 requested changes

2023-02-23 22:29 UTC, rgomezp commented on src/sw/serviceWorker/ServiceWorker.ts
> +      (event as FetchEvent).waitUntil(ServiceWorker.onPushSubscriptionChange(event as unknown as SubscriptionChangeEvent));
Typescript removed support for `PushSubscriptionChangeEvent` in 4.4 unfortunately, and putting `SubscriptionChangeEvent` directly as the type for the `event` causes the `addEventListener` function to complain. I was unable to find a replacement and looking directly at `lib.webworker.d.ts`, there is no equivalent that I can see (look for `oldSubscription`, `newSubscription`).

Do you know any alternative solutions?

2023-02-23 22:30 UTC, rgomezp commented
> Looks like a number of files (the ones in `support/mocks/models/` like `MockPushManager.ts`) are not new in this PR but rather just moved. Can we make a change in this PR so it shows up as moves? Might be able to just delete the old files to get that to show, or might have to do `git mv`

Done

2023-02-23 22:31 UTC, rgomezp commented on __test__/unit/core/modelRepo.test.ts
> +      passIfBroadcastNTimes(1, broadcastCount, done);
Good point. Jest will not fail in this case

2023-02-24 00:30 UTC, jkasten2 commented on src/sw/serviceWorker/ServiceWorker.ts
> +      (event as FetchEvent).waitUntil(ServiceWorker.onPushSubscriptionChange(event as unknown as SubscriptionChangeEvent));
We have `export interface SubscriptionChangeEvent` in `src/sw/serviceWorker/types.ts` that is breaking this. After removing VSCode shows no errors when doing this now:
```ts
    self.addEventListener('pushsubscriptionchange', (event: SubscriptionChangeEvent) => {
      event.waitUntil(ServiceWorker.onPushSubscriptionChange(event));
    });
```

2023-02-24 20:15 UTC, jkasten2 commented on __test__/unit/core/modelRepo.test.ts
> +      passIfBroadcastNTimes(1, broadcastCount, done);
The problem with that though is it makes this test fragile (passing when it shouldn't), as if that timeout handling changes in the future this test wouldn't catch that.

2023-02-24 20:49 UTC, jkasten2 commented on src/sw/serviceWorker/ServiceWorker.ts
> +      (event as FetchEvent).waitUntil(ServiceWorker.onPushSubscriptionChange(event as unknown as SubscriptionChangeEvent));
It was discovered that Typescript definition for  `pushsubscriptionchange` [is wrong](https://github.com/microsoft/TypeScript/blob/main/lib/lib.webworker.d.ts#L3128) and isn't defined to what it is in the [w3c spec](https://w3c.github.io/push-api/#the-pushsubscriptionchange-event). Given this the code we have here seems to be needed to work around this issue. There isn't a clear way to correct wrong typescript definitions at the project level.

2023-02-24 20:50 UTC, jkasten2 commented on __test__/unit/core/modelRepo.test.ts
> +      passIfBroadcastNTimes(1, broadcastCount, done);
Didn't understand the `done` until now. This covers what I was talking about above, if `done` is never called the test will fail. What we have here works.

2023-02-24 20:51 UTC, jkasten2 approved these changes

2023-02-24 20:51 UTC, merged